### ISSUE TITLE
API error using new API key structure

### ISSUE THREAD

**Issue by timpwhite** [gexijin/RTutor#100]
I'm encountering an issue with my API key in the Shiny App using the R console in R Studio. When I paste my key into the "Paste your API key from OpenAI" field, I get the error message "That does not look like a valid key!".

I understand that OpenAI has recently updated their API key format to include dashes, underscores, and additional characters.  Could the Shiny App's validation be outdated and not recognize the new format?

**Comment by dan-burk** [comment]
Our App's validation was running into errors with the change of OpenAI's API key format. We will have that fixed soon. Thanks for letting us know about the issue!

**Comment by dan-burk** [comment]
This should be fixed now.
