### ISSUE TITLE
Cannot find RTutor if running inside Docker

### ISSUE THREAD

**Issue by AleSR13** [gexijin/RTutor#44]
Hello! Thanks for making this very nice app! I was testing it today and the installation worked flawlessly in my local computer. However, it is not working inside a docker container. It may be out of the scope of your repo, but I thought maybe you would have an  idea on how to fix this issue. 

I used the `rocker/shiny` image as base and this is my Dockerfile. I realized that the `run_app()` function was using different ports every time so I asked it to use the `port = 8050` always. 

```
FROM rocker/shiny:4

RUN R -e "install.packages('remotes', dependencies = TRUE)"
RUN R -e "remotes::install_github('jcrodriguez1989/heyshiny', dependencies = TRUE)"
RUN R -e "remotes::install_github('gexijin/RTutor', dependencies = TRUE)"

RUN useradd -ms /bin/bash RTUTOR
USER RTUTOR

WORKDIR /data

EXPOSE 8050
CMD ["R", "-e", "RTutor::run_app( options = list('port' = 8050) )"]

```

Then I run the docker image like this, making sure I map the correct ports:

```
docker build -t rtutor .
docker run  -p 8050:8050 rtutor
```

**Output from docker run**:

```
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> RTutor::run_app( options = list('port' = 8050) )
Loading required package: shiny

Listening on http://127.0.0.1:8050
```

The app seems to run fine and the output says it is being directed to the right port but I simply cannot find it in my `localhost:8050`. I have tried changing the way I run it in many different ways, changing the ports, etc., all without avail. I wonder whether you have an idea about how to set it up. Is there something I am missing in the settings? The original docker image comes with some Shiny server that you can run like this

```
docker run -p 8050:3838 rtutor /init
```

That one runs without issues in `localhost:8050`. Any ideas? Thanks and sorry if this is completely out of scope!

**Comment by gexijin** [comment]
It is tricky to run inside a Docker container.  I am not very familiar with Docker files. 
1. Make sure the dependent R packages are preinstalled.   
   I typically log in to the container interactively and install them manually, as some does not auto install.
2. Make sure the API key is available in the container either as a file or as an environmental variable. 
3. There is a docker image for an older version of RTutor https://hub.docker.com/r/gexijin/rtutor/tags
4. My web server configuration is available here: https://github.com/gexijin/RTutor_server      The dockerfile is there. I also have a load balancer. I am not sure it helps.
