### ISSUE TITLE
Error with some plots although code is correct

### ISSUE THREAD

**Issue by AleSR13** [gexijin/RTutor#47]
Hi again!!

I have been playing with RTutor and I discovered something that I consider a bug. I uploaded a dataset (cannot share because it has sensitive data) and I asked a simple question. The question was this (I changed just col names):

> filter patients by “AwesomeValue” in col_1 column. Plot col_2 vs. col_3 and stratify or color points by col_4 column

FYI, the col_1 is a string (could be read as factor), the col_2 and col_3 are numeric and the col_4 is a boolean (containing 1 and 0, so it is read as integer).

The code generated was perfectly fine! I checked it running it myself in an Rmarkdown notebook.

```
# filter patients by “NSCLC” in cohortnm column
df_AwesomeValue <- df %>%
  filter(col_1 == "AwesomeValue")

# Plot col_2 vs. col_3 mRNA and stratify or color points by col_4 column
ggplot(df_AwesomeValue, aes(x = col_2, y = col_3, color = col_4)) +
  geom_point() +
  labs(x = "col_2", y = "col_3") +
  ggtitle("col_2 vs. col_3 mRNA Stratified by col_4")
```

However, when RTutor runs it, it fails and I get this error:

```
Error: An error has occurred. Check your logs or contact the app author for clarification.
```

When I check the logs on my terminal I see this is the actual error message:

```
Error in geom_point() : Problem while computing aesthetics.
ℹ Error occurred in the 1st layer.
Caused by error in `FUN()`:
! object 'col_2' not found
Warning: Error in geom_point: Problem while computing aesthetics.
```

So the tidy evaluation does not seem to work. In your examples, there are other plots that use `ggplot2` and use the tidy evaluation also and the objects are properly recognized as being a column. Anyway, not sure whether you manage to reproduce it without having the dataset but happy to explain more or show you by video call if necessary.

**Comment by gexijin** [comment]
I noticed similar issues, sometimes. I will look into this.
I really appreciate your feedbacks. Could we do a 30 minute video conference, so that I can get more feedback from you on this and RTutor in general? my email gexijin@gmail.com. 
If you are busy, that's fine. We can just communicate this way. 
Thanks Steven

**Comment by AleSR13** [comment]
Just sent you an email! 😃

**Comment by gexijin** [comment]
This happens occasionally. 
Looks like some extra character in the code. 
Error! <text>:4:1: unexpected input 3: 4: ^

**Comment by gexijin** [comment]
I think I found the issue. Sometimes, ChatGPT returns code in this form with \r\n as new lines. The \r is causing problem.
```
 [1] "\r"
 [2] "# Load necessary libraries\r"
 [3] "library(tidyverse)\r"
 [4] "\r"
 [5] "# Convert categorical variables to factors\r"
 [6] "df$cut <- as.factor(df$cut)\r"
 [7] "df$color <- as.factor(df$color)\r"
 [8] "df$clarity <- as.factor(df$clarity)\r"
 [9] "\r"
```

**Comment by gexijin** [comment]
Fixed.
