### ISSUE TITLE
option to change ip address

### ISSUE THREAD

**Issue by MartinChiaHsinLiu** [gexijin/RTutor#62]
Hi Steven,

Thank you for developing this wonderful tool.
Currently, RTutor start a shiny using 127.0.0.1:[random port].
I would like to change the IP address but I do not know how to set it.
I tried run_app(port="10.100.128.67")  but did not work.

Thank you in advance for your help!
Best Regards,
Martin

**Comment by gexijin** [comment]
Hi Martin, 
You can specify port number. See https://github.com/gexijin/RTutor/issues/45
But I am not sure if you can change ip address. 
RTutor is developed using Golem framework. You can search for possible solutions. 
https://github.com/ThinkR-open/golem
