### ISSUE TITLE
Error in if: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by PNewbury** [gexijin/RTutor#63]
Hello,

When trying to start, this is what happens:
> run_app()
Listening on http://127.0.0.1:4433
Warning: Error in if: missing value where TRUE/FALSE needed
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>

... The shiny ?container? opens and looks good for about 1 frame. Then it closes immediately, and I don't get control of the console back unless I hit esc in RStudio. I have tried running it in R natively, and it opens to a chrome website. However, the site is immediately greyed out. Same error. I can navigate the website, but I can't submit feedback or query cgpt. I have verified that shiny functions normally. Others with similar shiny issues have reported vaguely server issues, which I'm sure could also be general connection issues. Any idea how I can fix it?

**Comment by gexijin** [comment]
Thanks for your feedback.
Are you using he docker container? Or are you installing it as an R package? Please provide more info on your system as well.

**Comment by PNewbury** [comment]
> Thanks for your feedback. Are you using he docker container? Or are you installing it as an R package? Please provide more info on your system as well.

Thanks for replying! I'm installing it as an R package. Running most recent version of R (4.3.1? or is it 4.1.3? The new one idk). The PC is windows 10, i7-8700, 32Gb ram, some quadro card. It's on a university network. No crazy windows-side firewalls or permissions issues. I have admin access.

**Comment by gexijin** [comment]
It's perhaps an older version that you installed causing problem. I will update today both the source and the Docker container.
