### ISSUE TITLE
shiny is grey and Submit button does not work

### ISSUE THREAD

**Issue by madsurgeon** [gexijin/RTutor#7]
I have installed as described. The shiny page opens and looks correct, but it is grey.
"Log", "Ask Me Anything" and "About" react and show the respective tabs.
However, "Submit" doesn't work.
It is running remotely on RStudio server.

**Comment by gexijin** [comment]
Please post the version of R and RStudio server.  The "About" tab has some info. If you can, try updating R to 4.2.2 and also update RStudio. Check if the API key is set up in the remote server. If error persists, please let me know. Thanks.
