### ISSUE TITLE
A test dataset is loaded but AI generated code Chunk #1 try to work with demo data columns

### ISSUE THREAD

**Issue by jwang-lilly** [gexijin/RTutor#84]
After entering prompt " Please upload test_data.csv" in the project folder, the AI generated code Chunk #1 is as follows.  My test_data.csv, which is supposed to be loaded to df, has its own columns but dis, city, highway from default dataset are still used in the code. The Results section is empty.  The EDA also display the default df content. I also tried prompt "Please upload test_data.csv and assign it to df.", the same results.  During the process, I used "Reset" button to start from beginning including paste in my API each time.  The same happened even if I restarted the app.

# Load necessary libraries
library(readr)
library(dplyr)
library(ggplot2)

# Load the data
df <- read_csv("test_data.csv")

# Summary statistics for numeric variables
summary_stats <- df %>%
  select(dis, city, highway) %>%
  summary()

# Frequency counts for categorical variables
freq_counts <- df %>%
  select(maker, model, year, cylinder, transmission, drive, fuel, type) %>%
  summarise_all(n_distinct)

# Print summary statistics and frequency counts
print(summary_stats)
print(freq_counts)

I then asked it to remove everything from session, here is the AI generated code:

# Remove default data from the session
rm(list = ls())

# Load necessary libraries
library(readr)
library(dplyr)
library(ggplot2)

# Load the data
df <- read_csv("test_data.csv")

# Summary statistics for numeric variables
summary(df[, c("dis", "city", "highway")])

# Frequency table for categorical variables
lapply(df[, c("maker", "model", "year", "cylinder", "transmission", "drive", "fuel", "type")], table)

**Comment by gexijin** [comment]
Thank you for this feedback. 
1. Data is automatically loaded into R. No prompting is needed. 
2. We need to reset the session before uploading a new file, unless the second file is going to be analyzed together with the first one.  The reset button also clears out all objects. No need to do it through prompts. 
3. I have made some improvements on the UI. https://github.com/gexijin/RTutor/commit/1d35a3b2f2f46d699a518eefa5f57cbe89123613

I am closing this issue for now. Please let me know if you still have issues.
