### ISSUE TITLE
error came I just paste the issue

### ISSUE THREAD

**Issue by lenavikander** [gexijin/RTutor#87]
after successfully going through the installation just before finishing it appeared this:

Conflicts ───────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package to force all conflicts to become errors

any advise? thank you !

**Comment by gexijin** [comment]
You can ignore these warnings.
