### ISSUE TITLE
File parsing issues - can't load non-numeric data.

### ISSUE THREAD

**Issue by jamesnemesh** [gexijin/RTutor#89]
Hi, this is a really interesting tool.  Unfortunately, I'm running into some issues using it for "real" data.

I've tried to upload a few files (that are generated from R data.frames via write.table, tab separated), and only the numeric columns are included.  Factors are data too!

Here some sample data:
[test.txt](https://github.com/gexijin/RTutor/files/14501905/test.txt)

When parsed the strings/factors are removed:
<img width="1334" alt="image" src="https://github.com/gexijin/RTutor/assets/4561831/79e0729f-bad6-4424-b97a-1738f99acab0">

Additionally, the column names are mutated (and forced to lower case).  The original column names:
> colnames (df)
[1] "DONOR"    "REP_IRVs" "NUM_SNPS" "CENSUS"

**Comment by dan-burk** [comment]
Hi,

Thanks for the feedback! For certain reasons we remove the first column in a dataset if it looks like an ID field. In the example of test.txt the DONOR column is a unique identifier, hence the reason RTutor is throwing it out. If you change one of the DONOR ID's to be the same as another ID, RTutor will recognize that column as a character variable and won't throw it out (see test2.txt).
[test2.txt](https://github.com/user-attachments/files/16430017/test2.txt)

If you have an example where RTutor isn't uploading factor/character columns that aren't unique identifiers, we would appreciate the feedback greatly.

As for the column names. By default we clean the column names of files uploaded by users. Would it be advantageous for the ability to opt out of cleaning & forcing lower case the attributes?

Thanks,
Daniel
